// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4uhfJsvyKh9txZ2FHxXaKpjSA-sgobXs',
    appId: '1:859172785483:web:9d143205f58f61161b6cce',
    messagingSenderId: '859172785483',
    projectId: 'dayover-ae9f5',
    authDomain: 'dayover-ae9f5.firebaseapp.com',
    storageBucket: 'dayover-ae9f5.appspot.com',
    measurementId: 'G-CD1HDLX8FB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpI6oRWi_LbQhDT7r6ecDATePzUy37Mng',
    appId: '1:859172785483:android:cd22cdfc33b733061b6cce',
    messagingSenderId: '859172785483',
    projectId: 'dayover-ae9f5',
    storageBucket: 'dayover-ae9f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAngQxIpxiWEkM5O9H61pRYtluhRSeALz0',
    appId: '1:859172785483:ios:7e880f04677636ba1b6cce',
    messagingSenderId: '859172785483',
    projectId: 'dayover-ae9f5',
    storageBucket: 'dayover-ae9f5.appspot.com',
    iosClientId: '859172785483-3aohh6dmo2knmo1cmkprpbh24cl6lqn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.dayOver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAngQxIpxiWEkM5O9H61pRYtluhRSeALz0',
    appId: '1:859172785483:ios:7e880f04677636ba1b6cce',
    messagingSenderId: '859172785483',
    projectId: 'dayover-ae9f5',
    storageBucket: 'dayover-ae9f5.appspot.com',
    iosClientId: '859172785483-3aohh6dmo2knmo1cmkprpbh24cl6lqn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.dayOver',
  );
}
